### ISSUE TITLE
Elimination of loops in dependency resolving

### ISSUE THREAD

**Issue by pspiagicw** [pspiagicw/groom#1]
## Problem

Current if 2 tasks contain each other as their dependency, the execution goes into a infinite loop.

```toml
[task.task1]
depends = [
    "task2"
]

[task.task2]
depends = [
    "task1"
]
```

The above `groom.toml` will fail to actually execute anything.

## Fix

Implement a topological sorting algorithm within the app, to remove any cyclic dependencies.
