### ISSUE TITLE
Add option to get PWD as a variable

### ISSUE THREAD

**Issue by pspiagicw** [pspiagicw/groom#8]
Added a inherited variable called `pwd` which would automatically be initialized with the current directory.

**Comment by pspiagicw** [comment]
80505a4 adds this feature.

Now you can use the `${pwd}` variable to get the current working directory.

See the example below

```toml
[task.doc]
description = "Build documentation"
# Uses the $(pwd) variable to get the current working directory
command = "docker run --rm -v ${pwd}:/work --user 1000:1000 pspiagicw/doc-generator"
```
