### ISSUE TITLE
Add support for changing directories

### ISSUE THREAD

**Issue by pspiagicw** [pspiagicw/groom#9]
We should provide option to change directory for a specific task

Example 
```toml
[task.goreland]
description = "Format the project"
directory = "deps/goreland" # Provide a path to change first.
command = "groom build"
```

**Comment by pspiagicw** [comment]
46fe697 adds this feature. The config parameter is `directory`.

Meaning, this should list all the gifs in the directory.

```toml
[task.list]
directory = "gifs"
command = "ls -al"
```
